### PR TITLE
socket moved as private member of Client

### PR DESCRIPTION
**Pull request by MarcoCiaramella**
Using one global socket does not allow multiple clients to connect. This fix allows instantiation and connection of two or more clients at the same time.

### CODE REVIEW

**Comment by arnabk** [comment]
@MarcoCiaramella Could you please revert all other changes except the code changes and I can merge into master and release a new version. Thanks for contributing

**Comment by MarcoCiaramella** [comment]
hello @arnabk I revert Readme .travis.yml .editorconfig. Please note I've also released my fork on npmjs two years ago

**Comment by MarcoCiaramella** [comment]
when you merge and do a new version I can remove my module from npm. thanks for your work!

**Comment by arnabk** [comment]
Can we keep the package name same?

**Comment by MarcoCiaramella** [comment]
yes the package has the same name but is under my npm account (scoped-user package)

**Comment by arnabk** [comment]
Unfortunately I cannot merge personal package name into main branch

**Comment by MarcoCiaramella** [comment]
close this. I'm going to create a new pull request

**Pull request closed without merging**
